version: "3"

tasks:
  test:
    cmds:
      - go clean -testcache
      - go test -v -race ./...
  cover:
    cmds:
      - go clean -testcache
      - go test -v -cover ./...

  staticcheck:
    cmds:
      - staticcheck ./...
